print("sup fucker")
print("what is your name hoe?")
myname= input()
print("its good to meet your bitch ass," + myname)
print("the length of your ugly ass nem is:")
print(len (myname))
print("what is your age?")
myage = input()
print("you will be " + str(int(myage) + 1) + " in a year")
